### ISSUE TITLE
How much db do i actually change?

### ISSUE THREAD

**Issue by aesthicc** [nodeful/eqMac2#108]
It's unclear to me how much it actually changes. I'm trying to emulate a preset i had in menuBUS.
![sc](https://user-images.githubusercontent.com/32882701/33439246-3d79ed68-d5ed-11e7-8477-998a2b0c999b.png)

 Also, my focusrite scarlett isn't an option in the eqMac2 output setting, it works when i select it in sound preferences so just FYI.

Thanks!

**Comment by nosluoc** [comment]
Came to ask this very same thing.

**Comment by romankisil** [comment]
As @nosluoc said each slider represents -24dB to +24dB of range. Thanks for reporting that some audio devices are not shown in the dropdown menu. I will look into it

**Comment by nosluoc** [comment]
@romankisil Would it be possible to include a legend on the side, indicating dB increments, similar to the screenshot the OP included?

**Comment by aesthicc** [comment]
I agree with @nosluoc , it would be helpful. Maybe show the value of the slider when moving it?

**Comment by nodeful** [comment]
I just made an update and you can now see the dB when you adjust your sliders. Closing issue

**Comment by aesthicc** [comment]
Looks great! Thank you for this free and open source app.

**Comment by nodeful** [comment]
You mean like decimal places like 2.4dB?
If so, I tried that and there is just not enough space to fit all those characters, starts looking like a mess. Imagine every line is like +10.7, all the numbers would seem like they are merged together

**Comment by aesthicc** [comment]
You could hide the decimal when it's set, but allow inputting a decimal value? Might be confusing though. 

Another option is something like this:

![screencap 2017-12-03 at 17 43 42](https://user-images.githubusercontent.com/32882701/33527451-a7ebc232-d851-11e7-985e-77e23dd3b3dc.png)

Or:

![screencap 2017-12-03 at 17 44 00](https://user-images.githubusercontent.com/32882701/33527455-b044fe9e-d851-11e7-87bc-c5f3ab5239ee.png)

**Comment by nodeful** [comment]
Yeah that would be good but only for super pro users. Most users would realistically just want 3 knobs for Bass, Mids and Highs and adjust those :D Anyway, I'm not going to make anymore feature updates to this repo. I am moving onto different project for now, and when I come back to eqMac I want to do a complete rewrite again.

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
