### ISSUE TITLE
Saving a preset sometimes does not work / deletes existing presets

### ISSUE THREAD

**Issue by albertor24** [nodeful/eqMac2#122]
When saving a new preset, sometimes existing presets disappear, or the new preset fails to save. 

Usually the previous preset selected (provided it is not "Flat") is the one that disappears, but on one occasion, all of them were gone.

Seems to be more likely to occur when first opening the app.
  
 Using 10 bands equalizer
  
Steps to reproduce (about 25% reproducible):
 
1. Create two presets: One with high 4K 8K and 16K (lets name it upper), and one with low 4K 8K 16K (name it lower)
2. Select "lower" and quit the app
3. Try to drag the equalizer's 8K to a lower position (only once, and do not keep dragging). Note that it fails to do so.
4. Select "upper"
5. Drag 8K and 16K down.
6. Save

Result:
All presets are gone
 

  
![bug_demo_480](https://user-images.githubusercontent.com/8810350/34760693-ba2e9a4e-f595-11e7-8a1c-64e354595013.gif)

**Comment by nodeful** [comment]
You are using an old version of eqMac

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
