### ISSUE TITLE
Bug: Eqmac attempts to mount its disk image whenever the application icon is clicked

### ISSUE THREAD

**Issue by Overc1ocker** [nodeful/eqMac2#127]
This gets annoying, because whenever I eject it, it reopens when I try to change an eq setting. Please fix

**Comment by nodeful** [comment]
Did you move the eqMac2.app into your ~/Applications directory?

**Comment by nodeful** [comment]
or did you run in from the `.dmg` file you downloaded?

**Comment by Overc1ocker** [comment]
Yes. It kept mounting anyway, until I deleted the Dmg file

**Comment by nodeful** [comment]
Don't see why it would do this, unless you ran the app from the .dmg the first time.

**Comment by Overc1ocker** [comment]
I have no idea either. It is not doing it anymore. Feel free to close the issue. It may have just been my computer or something

**Comment by nodeful** [comment]
Other users have also reported this but I think everyone can solve this issue manually. Will keep in mind for next update

**Comment by Overc1ocker** [comment]
Thanks. Love your eq. Keep jamming out to ur fav tunes!

**Comment by JHarrisonEcoEvo** [comment]
I am having this issue too. Copied the app to my applications folder and unmounted the disk image. Always remounts the image when I load the app.

**Comment by JHarrisonEcoEvo** [comment]
fixed by quitting app, unmounting image, and deleting the image from within /volumes

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
