### ISSUE TITLE
First thing it does: Ask for root password

### ISSUE THREAD

**Issue by forthrin** [nodeful/eqMac2#136]
I was excited to find an open source equalizer for Mac, but when the first thing that happens when I run the app is being asked for my root password, I get wary.

Would it be able to change the app to function without elevated privileges? This would eliminate any worries one might have about security, and make the app more user friendly in general.

**Comment by nodeful** [comment]
macOS allows You to process Audio Files or Input Devices without installing any proprietary drivers, however, that's not the case with the System Audio. There is no known way to Route system audio without a HAL driver and you need the system password to install one.

**Comment by forthrin** [comment]
@nodeful: Very few apps and utilities I use ask for the root password. An exception is VirtualBox, which is widely known, and thus easily trusted.

This app I stumbled across and had never heard of. Granted, it's open source on Github, and I already had a look at the code and script, but the kext is a binary, so who knows what's going on in there.

Can anything be done to instil more trust into the user? For example, show the interface so the user sees that it contains a minimum of intricacy, not just some cheap attempt at installing spyware?

The user could even play around with the controls and everything, but to actually enable audio processing, you have to click a power button in the GUI, which shows a dialog:

> $OSNAME requires your root password to install a HAL driver for manipulating system audio.
> [________________]
> [Install] [View source] [Cancel]
> Worried about security? Feel free to check out the source code.

**Comment by nodeful** [comment]
The source for the driver is here: https://github.com/nodeful/eqMac2/tree/master/eqMac2Driver
I am not planning to add any more changes to this repository. I made this repo open-source because I currently dedicate all my time to a startup, and working on a new and very modern update of eqMac. My hope was that people who really care will have the ability to contribute themselves.

**Comment by forthrin** [comment]
I understand your priorities and good luck with that! A point of advice: Name and design the equalizer so that it looks like something that could have been a native part of macOS. The more generic (but pretty) looking such things are, the better. I for one tend to shy away from apps with weird names and design with a very "custom" look and feel.

**Comment by arpitchauhan** [comment]
@nodeful Am I right in assuming that the kext (kernel extension) binary that is installed at start (and is located at https://github.com/nodeful/eqMac2/tree/master/eqMac2/Supporting%20files/eqMac2Driver.kext) is created by compiling the code that you linked (https://github.com/nodeful/eqMac2/tree/master/eqMac2Driver). If yes, is there a way one can compile the kext oneself?

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
