### ISSUE TITLE
install an equalizer for ZTE Smartphone

### ISSUE THREAD

**Issue by crazyclay55** [nodeful/eqMac2#141]
Hello :) Before you create an issue please read the following message:

My name is Roman and I'm the only developer of this app.

I will NOT contribute any more code to this repository ever again. 

This repository is mostly for sharing the knowledge I gained during development.

At the moment I dedicate all my time to a startup and working on a new and very modern update to eqMac.

This new update will be completely rewritten from scratch and have many more new features and will be massively more stable (at least that't the plan).

I plan to release the new version in Q3 of 2018. 

Thank you for your patience and giving eqMac a go :)

If you need help with eqMac please join our Slack Group:

https://join.slack.com/t/eqmac/shared_invite/enQtMjk4NDkwNzEzOTA4LTg4OWFlYWFjNGQzZTJiM2RmMDI4MTUzMjk5ZTk1ZTkwYzk5NTk1ZDMwNTc1ZmU2MDdmNzRhNjc4ZTBhOWM2MzA

That's your best bet at getting some help from me or the community. 
GitHub is only for source-code related issues.

Still would like to report a bug or suggest a feature I can implement in the next version? 

Please make sure you search through the Open and Closed Issues people have already submitted:

https://github.com/nodeful/eqMac2/issues?utf8=%E2%9C%93&q=is%3Aissue+

This eliviates the posibility of people creating duplicate issues.

**Comment by nodeful** [comment]
get out of here

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
