### ISSUE TITLE
Airplay not supported

### ISSUE THREAD

**Issue by reuschp** [nodeful/eqMac2#162]
Hi there,

thanks for the great app. Works fine on the MacBook.

However it dos not work with Airplay.
I have to "choose" the output to eqMac2 to use the app. But I cannot "simultaneously" chaos Airplay.

<img width="238" alt="image" src="https://user-images.githubusercontent.com/41440181/55686491-33121180-5962-11e9-9434-72e9b5b23a25.png">

If I start the eqMac2 App during a running Airplay Stream, the connection to the speaker terminates. After that the app terminates. If I then use the MacBook Speakers and start eqMac2 again it works fine with the built-in speakers. 

I expected to see the external Speakers within the dropdown menu of the app - but there I can only see the build-ins.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/41440181/55686527-be8ba280-5962-11e9-85fb-b69c12931244.png">

So sadly no chance to improve my Airplay Sound...

Any suggestions?

Thanks
Pascal

Hello :) Before you create an issue please read the following message:

My name is Roman and I'm the only developer of this app.

I will NOT contribute any more code to this repository ever again. 

This repository is mostly for sharing the knowledge I gained during development.

At the moment I dedicate all my time to a startup and working on a new and very modern update to eqMac.

This new update will be completely rewritten from scratch and have many more new features and will be massively more stable (at least that't the plan).

I plan to release the new version in Q3 of 2018. 

Thank you for your patience and giving eqMac a go :)

If you need help with eqMac please join our Slack Group:

https://join.slack.com/t/eqmac/shared_invite/enQtMjk4NDkwNzEzOTA4LTg4OWFlYWFjNGQzZTJiM2RmMDI4MTUzMjk5ZTk1ZTkwYzk5NTk1ZDMwNTc1ZmU2MDdmNzRhNjc4ZTBhOWM2MzA

That's your best bet at getting some help from me or the community. 
GitHub is only for source-code related issues.

Still would like to report a bug or suggest a feature I can implement in the next version? 

Please make sure you search through the Open and Closed Issues people have already submitted:

https://github.com/nodeful/eqMac2/issues?utf8=%E2%9C%93&q=is%3Aissue+

This eliviates the posibility of people creating duplicate issues.

**Comment by nodeful** [comment]
https://github.com/nodeful/eqMac2/issues/164

**Comment by nodeful** [comment]
Hey everyone. Excuse me for the lack of updates. I have been really busy on the new version of eqMac. I am happy to announce an open beta release. 
You can download it here: https://eqmac.app
There are a lot of known bugs that I could not fix just yet:

- Driver not installing from the first try. Sometimes need to restart eqMac a couple times.
- Complex Device switching logic is not perfect (for example when switching off the device that's currently playing, plugging in new device etc.)
- UI takes long to load (a lot can be done to improve that)
- UI dimensions are not synching properly
- There's a noticeable audio delay in the playback, so not suitable for video yet (I know where the problem lies just haven't had the time to fix yet)
- Sometimes the playback doesn't start, in that case please try to switch the output to the device you want and eqMac should try and build the audio pipeline again.

So as you can see there's still some work to be done but at least it's a completely modern tech stack that I am fully willing to work on: 100% Swift, User Space driver and a Web UI, instead of C++, Kernel Drivers. As I said, should work on Catalina and should not have any pesky ear drum blasting volume bugs (at least I didn't come across any).
I'm open to feedback and issue reports here: https://github.com/bitgapp/eqmac
That repo will become the main repo for eqMac and this repo will be archived eventually.
And yes it's called just eqMac, not eqMac3 :) And it will stay that way forever.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by Rastafabisch** [comment]
Now, as this has been migrated to [bitgapp/eqMac](https://github.com/bitgapp/eqMac/issues/162) you might want to reopen this issue, as it is still valid.

**Comment by 1ecstasy** [comment]
Hello,
I can confirm this is still an issue in v1.3.2.

When starting eqmac it creates an audio device which for a reason I cannot understand is called exactly the same as my airplay device.
![image](https://user-images.githubusercontent.com/18720840/149625603-38785e39-b569-4a98-88dd-3aac62788249.png)

In eqmac then, you cannot select airplay devices:
![image](https://user-images.githubusercontent.com/18720840/149625638-82af3abb-b03d-4fcb-acec-3e69f6c1eb84.png)

Would be great if that worked. If I can help with any logs e.g. let me know.

**Comment by masonjames** [comment]
Is AirPlay2 in the works?

**Comment by dhvcc** [comment]
AirPlay seems to still not be working

**Comment by Dima-Kal** [comment]
Why is this closed? not working

**Comment by ragauskl** [comment]
Looking at the last comment before closure it seems that it was closed because Airplay support was not part of the plans. 

In any case there's another open issue about this https://github.com/bitgapp/eqMac/issues/390 so no need to open this as it would be duplicate.

Airplay support is not part of plans in near future, it may be added later down the road maybe. The core issue is the way macOS exposes interaction with the Airplay making it complicated to implement that in non native view/UI.
